### ISSUE TITLE
Not Loading Correctly

### ISSUE THREAD

**Issue by tfuGhost** [XXXBold/PCSX2_MultiConfigTool#2]
As long as I have any configs previously made custom configs inside the "User Config Path", the MultiConfigTool doesn't load correctly.  If I move all the configs I previously made with the MultiConfigTool, it starts starts working again.

I made the configs using the tool and there is nothing in the folder that wasn't previously made using the MultiConfigTool. But every time I want to use the application, I have to remove any previously made custom configs out of the folder first.

The attached image is the bug. Loading MultiConfigTool with previously made configs breaks the UI
![Capture](https://user-images.githubusercontent.com/66293566/83481739-e4b6bf00-a4e1-11ea-8eb6-888a6455f2dd.PNG)

**Comment by XXXBold** [comment]
(Sorry for long reaction time - didn't get any notification)

This seems like desired behaviour, if I understand correctly. The tool requires an empty folder or a folder containing configs which where made by the tool previously. If you manually create a Folder and copy some config-folders there, and select this folder, you should get a warning that the selected folder is not valid.

The reason for this is because the Tool creates an empty file named .pcsx2CFG to indicate the folder containing configs. If I won't do that, you could select any folder as your config path, which doesn't make sense and might even be dangerous, because you might accidently modify/delete stuff from your drive. So if you want your custom folder to be recognized, create the following file in it: "your-path/.pcsx2CFG". After that you should be able to select it within the tool. Are you using the most recent version?

**Comment by XXXBold** [comment]
Since I got no further response, gonna close this. Feel free to reopen if issue still persists.
